### ISSUE TITLE
Runtime UnhandledPromiseRejection

### ISSUE THREAD

**Issue by virajsoni06** [bentonow/bento-node-sdk#1] opened 2021-09-08 08:16 UTC
Hey @jessehanley @shadyendless, facing issues when using the bento library in a node app. I'm not able to pin point to where the error is coming from but this is what I get when I call `bento.V1.addSubscriber`
![image](https://user-images.githubusercontent.com/13236286/132472332-35938994-f4ad-40f0-832d-12d1e8a92d35.png)

Here's the Bento config which is calling addSubscriber
![image](https://user-images.githubusercontent.com/13236286/132472388-81736b68-c9ff-49ee-8d32-37342d310094.png)

Can you please help sort this out. Thanks

**Comment by shadyendless** [comment] 2021-09-08 08:35
Hello @virajsoni06!

I am trying to reproduce this error but I am having troubles. Here is the code I am running locally to attempt to reproduce this error:

```ts
const { Analytics } = require('@bentonow/bento-node-sdk');

(async () => {
    try {
        const bento = new Analytics({
            authentication: {
                secretKey: 'xxx',
                publishableKey: 'xxx',
            },
            siteUuid: 'xxx',
        });

        const subscribeToBento = async ({ payload }) => {
            await bento.V1.addSubscriber({
                email: payload.email,
                fields: {
                    firstName: payload.firstName,
                    lastName: payload.lastName,
                    name: `${payload.firstName} ${payload.lastName}`,
                },
            });

            await bento.V1.trackPurchase({
                email: payload.email,
                purchaseDetails: {
                    unique: {
                        key: payload.subscriptionId,
                    },
                    value: {
                        currency: payload.currency_code,
                        amount: payload.amount,
                    },
                },
            });

            return;
        };

        await subscribeToBento({
            payload: {
                email: 'virajsoni06@test.com',
                firstName: 'Vira',
                lastName: 'Jsoni',
                subscriptionId: '1234567890',
                currency_code: 'USD',
                amount: 1500,
            },
        });
    } catch (e) {
        console.log(e);
    }
})();
```

And here is the resulting creation of the subscriber in Bento:
![image](https://user-images.githubusercontent.com/1154812/132475360-9afe8bcc-0ed7-4b98-88f0-e12522bda385.png)

Could you please provide some more information as to how you are using it? More specifically, how you are importing the library and where you are calling the `subscribeToBento` method.

Thanks!

**Comment by virajsoni06** [comment] 2021-09-08 08:49
@shadyendless We've got a serverless function which is importing the Bento instance and attempting to call the subscribeToBento method.

Here's how it's setup. I'm simply importing the functions and calling them in the serverless api call
![image](https://user-images.githubusercontent.com/13236286/132477615-2a62d688-cdad-4758-b64a-921461c928c2.png)

Could it be that the bento instance is not ready while calling `subscribeToBento`?

**Comment by virajsoni06** [comment] 2021-09-08 08:52
Unlikely its caused due to bento instance not being ready. Moved bento instance inside the subscribeToBento function and still getting the same error

![image](https://user-images.githubusercontent.com/13236286/132478386-652206bf-f348-4e42-97dd-23832ac571c0.png)

**Comment by shadyendless** [comment] 2021-09-08 08:55
It's hard to say as it depends on where those are being called. The SDK surfaces any errors it encounters back to the call site, and so if you are using the `async/await` syntax then you'll want to wrap the call to `subscribeToBento` in a `try {} catch {}` to see what the error is that is coming out.

If you are using the standard Promise interface, then it would be something like 
```js
subscribeToBento().catch(error => console.error(error))
```

I see that you are directly exporting the functions that you created (which is the recommended way to do things), but can you see where those are then being imported and called? I am not sure of a serverless environment which can directly call those on their own as they exist (as their parameters do not match the typical function handlers I am familiar with).

**Comment by shadyendless** [comment] 2021-09-08 09:11
@virajsoni06 realized I didn't tag you on my previous comment so I am not sure if you received a notification. Checking in to see if the above suggestions helped or resulted in any more details surrounding the error.

**Comment by virajsoni06** [comment] 2021-09-08 09:45
Hey @shadyendless, tested with try catch block as well as updating the calls with Promise interface. The errors still persists
![image](https://user-images.githubusercontent.com/13236286/132486235-1173652f-226f-4704-b854-3fe8ea31d451.png)

Re the serverless stuff, it's pretty straight forward. The api endpoint is creating accounts on our another system and then we call subscribeToBento function afterwards
![image](https://user-images.githubusercontent.com/13236286/132486502-2a60f38b-3470-4d0c-b78f-ff9c55f235f2.png)

---


Can you send more debugging information in errors to site calling it? Also can we see if the api calls are hitting bento and what is received from its end? @jessehanley

**Comment by shadyendless** [comment] 2021-09-08 10:19
@virajsoni06 I can update it so that it just wraps the error that it receives and returns that back up. I am wondering if it is getting an unauthenticated error or something to that nature.

Does this code work if you run it locally versus in the lambda? Are you sure that your Bento instance is being created  with the proper secret key, public key, and site ID?

**Comment by shadyendless** [comment] 2021-09-08 10:53
I'm trying everything I can think of on my end to try and reproduce this error and I'm not having any luck. Let me know if you're able to reproduce it locally and, if you can, would you mind creating a repo or something where I could easily run the code that is producing the error?

**Comment by virajsoni06** [comment] 2021-09-08 14:26
@shadyendless Authentication is correct, it's throwing internal server errors
![image](https://user-images.githubusercontent.com/13236286/132527931-2e4a0ff1-fbfe-4e6f-8448-42f468ad1fe4.png)


Can't you check in Bento's server logs to see incoming requests?

**Comment by jessehanley** [comment] 2021-09-08 22:05
@virajsoni06 can you message me the keys you're using over on Discord? Just want to confirm they are correct.

**Comment by shadyendless** [comment] 2021-09-09 02:08
> @shadyendless Authentication is correct, it's throwing internal server errors
> ![image](https://user-images.githubusercontent.com/13236286/132527931-2e4a0ff1-fbfe-4e6f-8448-42f468ad1fe4.png)
> 
> Can't you check in Bento's server logs to see incoming requests?

Can you DM me the exact payload that you are trying to send across on Discord? Just do a `JSON.stringify` of it or something and toss it over my way. I'm going to update the internal server error API call so that it wraps  the response back from the server and sends it up as well. This may take me some time as my full-time job is not with Bento, but I'll try and get something together as soon as I can (should be sometime today in Japan time).

**Comment by shadyendless** [comment] 2021-09-09 02:45
Worked on this a little bit, the most I can get back from the API is either a 401 (Unauthorized error), or a 500 (Internal server error). The response body back from the 500 is:
```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

Which doesn't help much in terms of a debugging aspect. That being said, I am having a lot of trouble getting this error to appear given the methods you've written and are calling. Once I have that payload I can help debug it in more detail, though.

You are receiving an Internal Server Error (you can see it in the screenshot you posted), and  the only way to receive this error that I see is by sending a malformed payload to the API, which this SDK does its best to prevent.

Outside of that, there may be other errors that you can get that I am not seeing given the account I am testing with. This may be something @jessehanley can help debug if you let him know which secret key, public key, and site ID you are using.

**Comment by jessehanley** [comment] 2021-09-09 06:02
@shadyendless confirming that his keys work fine, tested manually using just my Ruby console.

**Comment by shadyendless** [comment] 2021-09-09 06:17
Alright, going to go ahead and close this issue. Not sure what was causing it but it seems resolved on @virajsoni06's end now after going through some steps on Discord.

Feel free to re-open the issue again or create a new one if it comes up again or we can figure out a reproduceable setup.

**Closed by shadyendless** 2021-09-09 06:17 UTC

**Comment by jessehanley** [comment] 2021-09-09 06:31
@shadyendless was it just a syntax bug?

**Comment by shadyendless** [comment] 2021-09-09 08:52
@jessehanley the code worked without being changed, and then it started throwing the errors again shortly after working. Not sure if there is just something going on with the API but I can't reproduce it no matter how hard I try.
